import type { Language } from '@/lib/i18n/dictionaries';

const en = {
  receiveMoney: 'Receive money',
  receiveHelp:
    'Share this receiving reference only with someone who is sending you money.',
  copyReference: 'Copy reference',
  copied: 'Copied',
  referenceCopied: 'Reference copied.',
  sendMoney: 'Send money',
  sourceAccount: 'Source account',
  recipient: 'Recipient AEGIS reference',
  amount: 'Amount (LKR)',
  preview: 'Preview transfer',
  review: 'Review transfer',
  from: 'From',
  to: 'To',
  available: 'Available balance',
  verify: 'Verify the masked recipient and amount before authorizing.',
  enterPin: 'Enter your PIN',
  confirm: 'Confirm transfer',
  edit: 'Edit details',
  invalid: 'Check the recipient reference and amount, then try again.',
  authorizationFailed:
    'Authorization failed or the transfer could not be completed.',
  wrongPin: 'The PIN was incorrect. Try again.',
  expired: 'The transfer preview expired. Create a new preview.',
  insufficient: 'The account does not have enough funds for this transfer.',
  dailyLimit: 'This transfer would exceed the daily transfer limit.',
  history: 'Transfer history',
  transfers: 'Transfers',
  sent: 'Sent',
  received: 'Received',
  none: 'No transfers yet.',
  unavailable: 'Transfer history is temporarily unavailable.',
  retained: 'Previously loaded transfers remain available. Try again later.',
  loadMore: 'Load more',
  direction: 'Direction',
  status: 'Status',
  allDirections: 'All directions',
  allStatuses: 'All statuses',
  applyFilters: 'Apply filters',
  back: 'Back to transfers',
  record: 'Prototype transfer record',
  reference: 'Transfer reference',
  counterparty: 'Counterparty',
  account: 'Account',
  created: 'Created',
  completed: 'Completed',
  resultingBalance: 'Resulting balance',
  processing: 'Transfer processing…',
  processingTimeout:
    'The transfer is taking longer than expected. Check transfer history before retrying.',
  notFound: 'Transfer not found.',
  print: 'Print',
  disclaimer:
    'This is a synthetic prototype record, not proof of payment or a financial instrument.',
} as const;
type TransferCopy = { [K in keyof typeof en]: string };

const si: TransferCopy = {
  receiveMoney: 'මුදල් ලබා ගන්න',
  receiveHelp: 'ඔබට මුදල් එවන පුද්ගලයා සමඟ පමණක් මෙම ලැබීමේ යොමුව බෙදා ගන්න.',
  copyReference: 'යොමුව පිටපත් කරන්න',
  copied: 'පිටපත් විය',
  referenceCopied: 'යොමුව පිටපත් විය.',
  sendMoney: 'මුදල් යවන්න',
  sourceAccount: 'මූලාශ්‍ර ගිණුම',
  recipient: 'ලබන්නාගේ AEGIS යොමුව',
  amount: 'මුදල (LKR)',
  preview: 'හුවමාරුව පෙරදසුන් කරන්න',
  review: 'හුවමාරුව සමාලෝචනය කරන්න',
  from: 'සිට',
  to: 'වෙත',
  available: 'ලබාගත හැකි ශේෂය',
  verify: 'අවසර දීමට පෙර සඟවා පෙන්වන ලබන්නා සහ මුදල තහවුරු කරන්න.',
  enterPin: 'ඔබේ PIN අංකය ඇතුළත් කරන්න',
  confirm: 'හුවමාරුව තහවුරු කරන්න',
  edit: 'විස්තර සංස්කරණය කරන්න',
  invalid: 'ලබන්නාගේ යොමුව සහ මුදල පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
  authorizationFailed:
    'අවසර දීම අසාර්ථක විය හෝ හුවමාරුව සම්පූර්ණ කළ නොහැකි විය.',
  wrongPin: 'PIN අංකය වැරදිය. නැවත උත්සාහ කරන්න.',
  expired: 'හුවමාරු පෙරදසුන කල් ඉකුත් විය. නව පෙරදසුනක් සාදන්න.',
  insufficient: 'මෙම හුවමාරුවට ගිණුමේ ප්‍රමාණවත් මුදල් නොමැත.',
  dailyLimit: 'මෙම හුවමාරුව දෛනික සීමාව ඉක්මවයි.',
  history: 'හුවමාරු ඉතිහාසය',
  transfers: 'හුවමාරු',
  sent: 'යැවූ',
  received: 'ලැබුණු',
  none: 'තවම හුවමාරු නොමැත.',
  unavailable: 'හුවමාරු ඉතිහාසය තාවකාලිකව නොමැත.',
  retained: 'කලින් පූරණය කළ හුවමාරු තවම ඇත. පසුව උත්සාහ කරන්න.',
  loadMore: 'තවත් පෙන්වන්න',
  direction: 'දිශාව',
  status: 'තත්ත්වය',
  allDirections: 'සියලු දිශා',
  allStatuses: 'සියලු තත්ත්ව',
  applyFilters: 'පෙරහන් යොදන්න',
  back: 'හුවමාරු වෙත ආපසු',
  record: 'මූලාකෘති හුවමාරු වාර්තාව',
  reference: 'හුවමාරු යොමුව',
  counterparty: 'අනෙක් පාර්ශ්වය',
  account: 'ගිණුම',
  created: 'සාදන ලදී',
  completed: 'සම්පූර්ණ විය',
  resultingBalance: 'ප්‍රතිඵල ශේෂය',
  processing: 'හුවමාරුව සැකසෙමින්…',
  processingTimeout:
    'හුවමාරුවට බලාපොරොත්තු වූවාට වඩා කල් ගත වේ. නැවත උත්සාහ කිරීමට පෙර ඉතිහාසය පරීක්ෂා කරන්න.',
  notFound: 'හුවමාරුව සොයාගත නොහැක.',
  print: 'මුද්‍රණය',
  disclaimer:
    'මෙය කෘතිම මූලාකෘති වාර්තාවක් පමණි; ගෙවීමේ සාක්ෂියක් හෝ මූල්‍ය උපකරණයක් නොවේ.',
};

const ta: TransferCopy = {
  receiveMoney: 'பணம் பெறுங்கள்',
  receiveHelp:
    'உங்களுக்கு பணம் அனுப்புபவருடன் மட்டும் இந்த பெறும் குறிப்பைப் பகிரவும்.',
  copyReference: 'குறிப்பை நகலெடுக்கவும்',
  copied: 'நகலெடுக்கப்பட்டது',
  referenceCopied: 'குறிப்பு நகலெடுக்கப்பட்டது.',
  sendMoney: 'பணம் அனுப்பவும்',
  sourceAccount: 'மூலக் கணக்கு',
  recipient: 'பெறுநரின் AEGIS குறிப்பு',
  amount: 'தொகை (LKR)',
  preview: 'பரிமாற்றத்தை முன்னோட்டமிடவும்',
  review: 'பரிமாற்றத்தை மதிப்பாய்வு செய்யவும்',
  from: 'இருந்து',
  to: 'பெறுநர்',
  available: 'கிடைக்கும் இருப்பு',
  verify:
    'அங்கீகரிக்கும் முன் மறைக்கப்பட்ட பெறுநரையும் தொகையையும் சரிபார்க்கவும்.',
  enterPin: 'உங்கள் PIN-ஐ உள்ளிடவும்',
  confirm: 'பரிமாற்றத்தை உறுதிப்படுத்தவும்',
  edit: 'விவரங்களைத் திருத்தவும்',
  invalid: 'பெறுநர் குறிப்பையும் தொகையையும் சரிபார்த்து மீண்டும் முயலவும்.',
  authorizationFailed:
    'அங்கீகாரம் தோல்வியடைந்தது அல்லது பரிமாற்றத்தை முடிக்க முடியவில்லை.',
  wrongPin: 'PIN தவறானது. மீண்டும் முயலவும்.',
  expired:
    'பரிமாற்ற முன்னோட்டம் காலாவதியானது. புதிய முன்னோட்டத்தை உருவாக்கவும்.',
  insufficient: 'இந்தப் பரிமாற்றத்திற்குக் கணக்கில் போதிய பணம் இல்லை.',
  dailyLimit: 'இந்தப் பரிமாற்றம் தினசரி வரம்பை மீறும்.',
  history: 'பரிமாற்ற வரலாறு',
  transfers: 'பரிமாற்றங்கள்',
  sent: 'அனுப்பியது',
  received: 'பெற்றது',
  none: 'இன்னும் பரிமாற்றங்கள் இல்லை.',
  unavailable: 'பரிமாற்ற வரலாறு தற்காலிகமாகக் கிடைக்கவில்லை.',
  retained: 'முன்பு ஏற்றிய பரிமாற்றங்கள் உள்ளன. பின்னர் முயலவும்.',
  loadMore: 'மேலும் ஏற்றவும்',
  direction: 'திசை',
  status: 'நிலை',
  allDirections: 'அனைத்து திசைகளும்',
  allStatuses: 'அனைத்து நிலைகளும்',
  applyFilters: 'வடிகட்டிகளைப் பயன்படுத்து',
  back: 'பரிமாற்றங்களுக்குத் திரும்பு',
  record: 'முன்மாதிரி பரிமாற்றப் பதிவு',
  reference: 'பரிமாற்றக் குறிப்பு',
  counterparty: 'எதிர்தரப்பு',
  account: 'கணக்கு',
  created: 'உருவாக்கப்பட்டது',
  completed: 'முடிந்தது',
  resultingBalance: 'முடிவு இருப்பு',
  processing: 'பரிமாற்றம் செயலாக்கப்படுகிறது…',
  processingTimeout:
    'பரிமாற்றம் எதிர்பார்த்ததைவிட நீள்கிறது. மீண்டும் முயல்வதற்கு முன் வரலாற்றைப் பார்க்கவும்.',
  notFound: 'பரிமாற்றம் கிடைக்கவில்லை.',
  print: 'அச்சிடுக',
  disclaimer:
    'இது செயற்கை முன்மாதிரி பதிவு மட்டுமே; கட்டணச் சான்றோ நிதிக் கருவியோ அல்ல.',
};

export const transferCopy: Record<Language, TransferCopy> = {
  EN: en,
  SI: si,
  TA: ta,
};
